"""add policy and injection columns to decisions

Revision ID: 18fba976fb20
Revises: 23c44c9eb977
Create Date: 2026-09-18 12:08:22.020760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fba976fb20'
down_revision: Union[str, None] = '23c44c9eb977'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('policy_id', sa.UUID(), nullable=True))
    op.add_column('decisions', sa.Column('policy_rule', sa.String(length=80), nullable=True))
    op.add_column('decisions', sa.Column('policy_effect', sa.String(length=20), nullable=True))
    op.add_column('decisions', sa.Column('injection_score', sa.Float(), nullable=False))
    op.create_index(op.f('ix_decisions_policy_id'), 'decisions', ['policy_id'], unique=False)
    op.create_foreign_key(op.f('fk_decisions_policy_id_policies'), 'decisions', 'policies', ['policy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_decisions_policy_id_policies'), 'decisions', type_='foreignkey')
    op.drop_index(op.f('ix_decisions_policy_id'), table_name='decisions')
    op.drop_column('decisions', 'injection_score')
    op.drop_column('decisions', 'policy_effect')
    op.drop_column('decisions', 'policy_rule')
    op.drop_column('decisions', 'policy_id')
    # ### end Alembic commands ###