"""remove unique constraint on tenant name

Revision ID: 28537e1f578b
Revises: 5ba0ae8d3c92
Create Date: 2026-09-21 00:11:13.257093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28537e1f578b'
down_revision: Union[str, None] = '5ba0ae8d3c92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_approvals_decision_id', table_name='approvals')
    op.create_index('ix_approvals_decision_id', 'approvals', ['decision_id'], unique=True)
    op.drop_constraint('uq_tenants_name', 'tenants', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tenants_name', 'tenants', ['name'])
    op.drop_index('ix_approvals_decision_id', table_name='approvals')
    op.create_index('ix_approvals_decision_id', 'approvals', ['decision_id'], unique=False)
    # ### end Alembic commands ###