"""add decisions table

Revision ID: 2ed36510fcfa
Revises: 2cd01783d45e
Create Date: 2026-09-17 23:42:54.266167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ed36510fcfa'
down_revision: Union[str, None] = '2cd01783d45e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tool', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_decisions_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_decisions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index('ix_decisions_agent_created', 'decisions', ['agent_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_decisions_agent_id'), 'decisions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_decisions_tenant_id'), 'decisions', ['tenant_id'], unique=False)
    op.create_index('ix_decisions_verdict_created', 'decisions', ['verdict', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decisions_verdict_created', table_name='decisions')
    op.drop_index(op.f('ix_decisions_tenant_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_agent_id'), table_name='decisions')
    op.drop_index('ix_decisions_agent_created', table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###