"""add approvals table

Revision ID: 4d85afb65b25
Revises: 7283b1009a54
Create Date: 2026-09-18 22:23:39.173543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d85afb65b25'
down_revision: Union[str, None] = '7283b1009a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('decision_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tool', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('request_context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_channel', sa.String(length=30), nullable=True),
    sa.Column('notification_error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_approvals_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_approvals_decision_id_decisions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approvals_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_agent_id'), 'approvals', ['agent_id'], unique=False)
    op.create_index('ix_approvals_decision_id', 'approvals', ['decision_id'], unique=True)
    op.create_index('ix_approvals_status_created', 'approvals', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_approvals_tenant_id'), 'approvals', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_tenant_id'), table_name='approvals')
    op.drop_index('ix_approvals_status_created', table_name='approvals')
    op.drop_index('ix_approvals_decision_id', table_name='approvals')
    op.drop_index(op.f('ix_approvals_agent_id'), table_name='approvals')
    op.drop_table('approvals')
    # ### end Alembic commands ###