"""add kill switches table

Revision ID: 5ba0ae8d3c92
Revises: 4d85afb65b25
Create Date: 2026-09-18 22:38:00.874207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ba0ae8d3c92'
down_revision: Union[str, None] = '4d85afb65b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kill_switches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activated_by', sa.String(length=120), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deactivated_by', sa.String(length=120), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivation_note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kill_switches'))
    )
    op.create_index(op.f('ix_kill_switches_is_active'), 'kill_switches', ['is_active'], unique=False)
    op.create_index(op.f('ix_kill_switches_scope'), 'kill_switches', ['scope'], unique=False)
    op.create_index('ix_kill_switches_scope_active', 'kill_switches', ['scope', 'is_active'], unique=False)
    op.create_index('ix_kill_switches_target_active', 'kill_switches', ['target_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_kill_switches_target_id'), 'kill_switches', ['target_id'], unique=False)
    op.drop_index('ix_approvals_decision_id', table_name='approvals')
    op.create_index(op.f('ix_approvals_decision_id'), 'approvals', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approvals_decision_id'), table_name='approvals')
    op.create_index('ix_approvals_decision_id', 'approvals', ['decision_id'], unique=True)
    op.drop_index(op.f('ix_kill_switches_target_id'), table_name='kill_switches')
    op.drop_index('ix_kill_switches_target_active', table_name='kill_switches')
    op.drop_index('ix_kill_switches_scope_active', table_name='kill_switches')
    op.drop_index(op.f('ix_kill_switches_scope'), table_name='kill_switches')
    op.drop_index(op.f('ix_kill_switches_is_active'), table_name='kill_switches')
    op.drop_table('kill_switches')
    # ### end Alembic commands ###