"""add pii columns to decisions

Revision ID: bfafc46d2ee7
Revises: 18fba976fb20
Create Date: 2026-09-18 12:22:01.786062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bfafc46d2ee7'
down_revision: Union[str, None] = '18fba976fb20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decisions', sa.Column('pii_classification', sa.String(length=20), nullable=True))
    op.add_column('decisions', sa.Column('pii_labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decisions', 'pii_labels')
    op.drop_column('decisions', 'pii_classification')
    # ### end Alembic commands ###